# Generated by Django 3.1.7 on 2021-08-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_name', models.CharField(max_length=200)),
                ('Item_desc', models.CharField(max_length=200)),
                ('Item_price', models.IntegerField()),
            ],
        ),
    ]
