# Generated by Django 3.1.7 on 2021-08-25 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Item_image',
            field=models.CharField(default='https://www.google.com/imgres?imgurl=https%3A%2F%2Fexplorelompoc.com%2Fwp-content%2Fuploads%2F2021%2F06%2Ffood_placeholder.jpg&imgrefurl=https%3A%2F%2Fexplorelompoc.com%2Fdirectory%2Fangelas-mexican-restaurant%2F&tbnid=DN3T1aE2A-l81M&vet=12ahUKEwihzva5pM3yAhXZ0oUKHV6AD4oQMygSegUIARDSAQ..i&docid=gwPtCsH8ej_UyM&w=800&h=800&q=placeholder%20image%20for%20food&ved=2ahUKEwihzva5pM3yAhXZ0oUKHV6AD4oQMygSegUIARDSAQ', max_length=500),
        ),
    ]
